services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doc-intelligence
    ports:
      - "5432:5432"
    volumes:
      - doc-intelligence-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  doc-intelligence-postgres: